services:
  api:
    image: wos-svs-manager-api
    container_name: wos-svs-manager
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3001
      - DOCKER=true
    restart: unless-stopped
