/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ImportRouteImport } from './routes/import'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PeriodsRouteImport } from './routes/periods'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as SlingshotRouteImport } from './routes/slingshot'
import { Route as PeriodsPeriodIdRouteImport } from './routes/periods.$periodId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodsRoute = PeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SlingshotRoute = SlingshotRouteImport.update({
  id: '/slingshot',
  path: '/slingshot',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodsPeriodIdRoute = PeriodsPeriodIdRouteImport.update({
  id: '/$periodId',
  path: '/$periodId',
  getParentRoute: () => PeriodsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/import': typeof ImportRoute
  '/messages': typeof MessagesRoute
  '/periods': typeof PeriodsRouteWithChildren
  '/players': typeof PlayersRoute
  '/scoring': typeof ScoringRoute
  '/slingshot': typeof SlingshotRoute
  '/periods/$periodId': typeof PeriodsPeriodIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/import': typeof ImportRoute
  '/messages': typeof MessagesRoute
  '/periods': typeof PeriodsRouteWithChildren
  '/players': typeof PlayersRoute
  '/scoring': typeof ScoringRoute
  '/slingshot': typeof SlingshotRoute
  '/periods/$periodId': typeof PeriodsPeriodIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/import': typeof ImportRoute
  '/messages': typeof MessagesRoute
  '/periods': typeof PeriodsRouteWithChildren
  '/players': typeof PlayersRoute
  '/scoring': typeof ScoringRoute
  '/slingshot': typeof SlingshotRoute
  '/periods/$periodId': typeof PeriodsPeriodIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/import'
    | '/messages'
    | '/periods'
    | '/players'
    | '/scoring'
    | '/slingshot'
    | '/periods/$periodId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/import'
    | '/messages'
    | '/periods'
    | '/players'
    | '/scoring'
    | '/slingshot'
    | '/periods/$periodId'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/import'
    | '/messages'
    | '/periods'
    | '/players'
    | '/scoring'
    | '/slingshot'
    | '/periods/$periodId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  ImportRoute: typeof ImportRoute
  MessagesRoute: typeof MessagesRoute
  PeriodsRoute: typeof PeriodsRouteWithChildren
  PlayersRoute: typeof PlayersRoute
  ScoringRoute: typeof ScoringRoute
  SlingshotRoute: typeof SlingshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periods': {
      id: '/periods'
      path: '/periods'
      fullPath: '/periods'
      preLoaderRoute: typeof PeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slingshot': {
      id: '/slingshot'
      path: '/slingshot'
      fullPath: '/slingshot'
      preLoaderRoute: typeof SlingshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periods/$periodId': {
      id: '/periods/$periodId'
      path: '/$periodId'
      fullPath: '/periods/$periodId'
      preLoaderRoute: typeof PeriodsPeriodIdRouteImport
      parentRoute: typeof PeriodsRoute
    }
  }
}

interface PeriodsRouteChildren {
  PeriodsPeriodIdRoute: typeof PeriodsPeriodIdRoute
}

const PeriodsRouteChildren: PeriodsRouteChildren = {
  PeriodsPeriodIdRoute: PeriodsPeriodIdRoute,
}

const PeriodsRouteWithChildren =
  PeriodsRoute._addFileChildren(PeriodsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  ImportRoute: ImportRoute,
  MessagesRoute: MessagesRoute,
  PeriodsRoute: PeriodsRouteWithChildren,
  PlayersRoute: PlayersRoute,
  ScoringRoute: ScoringRoute,
  SlingshotRoute: SlingshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
